services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: aieditor_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
  aieditor-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '${API_PORT:-3030}:${API_PORT:-3030}'
    environment:
      - API_PORT=${API_PORT}
    volumes:
      - ./:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
